---
- name: yarn リポジトリをインストール
  shell: curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo -o /etc/yum.repos.d/yarn.repo
  become: yes

- name: yarn インストール
  # nvm nodejs / yum yarn の組み合わせだと無理なのでInstallation Script
  # 以下の環境変数が追加される
  # export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  #
  shell: /bin/bash -lc "curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0"
  # yum: name=yarn state=present skip_broken=yes
  become: yes

