---
- name: yarn リポジトリをインストール
  shell: curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo -o /etc/yum.repos.d/yarn.repo
  become: yes

- name: yarn インストール
  yum: name=yarn state=present skip_broken=yes
  become: yes

